name: CD Production

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Production
        uses: ./.github/actions/deploy
        with:
          HEROKU_USER: ${{ secrets.HEROKU_USER }}
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
          HEROKU_PROJECT: greyboard