name: CD

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize job
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2.5.1

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | bash

      - name: Build Docker Image
        run: docker build -t registry.heroku.com/greyboard/web .

      - name: Login to Heroku Registry
        run: docker login -u ${{ secrets.HEROKU_USER }} -p ${{ secrets.HEROKU_TOKEN }} registry.heroku.com
      
      - name: Push Image to Heroku
        run: docker push registry.heroku.com/greyboard/web

      - name: Start the App on Heroku
        run: docker run --rm -e HEROKU_API_KEY=${{ secrets.HEROKU_TOKEN }} wingrunr21/alpine-heroku-cli container:release web --app greyboard
